---
   ---
    - name: Config Web VM with Docker
      hosts: webservers
      become: true
      tasks:
      - name: docker.io
        apt:
          force_apt_get: yes
          update_cache: yes
          name: docker.io
   ---
     - name: Install Docker.io
       apt:
        name: docker.io
        update_cache: yes
        state: present

     - name: Install Python3-Piop
       apt:
        name: python3-pip
        state: present

     - name: Download the web DVWA Containers
       docker_container: 
